"""Django settings for user service.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: PROJECT_ROOT / 'subdir'.
# PROJECT_ROOT, aka BASE_DIR.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add parent directory to path for common imports
sys.path.insert(0, str(PROJECT_ROOT.parent))

# Load environment variables from .env file
load_dotenv(dotenv_path=PROJECT_ROOT / '.env')

# Import common settings
from common.settings.base import (  # noqa: E402, F401
    COMMON_AUTH_PASSWORD_VALIDATORS,
    COMMON_INSTALLED_APPS,
    COMMON_JAZZMIN_SETTINGS,
    COMMON_MIDDLEWARE,
    COMMON_TEMPLATE_CONTEXT_PROCESSORS,
    DEFAULT_AUTO_FIELD,
    LANGUAGE_CODE,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-ku-j+zx16yg_lyrpt)ohcm-2rldm0z23vaa0#p66vxlni=@nj8',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1']

ALLOWED_HOSTS: list[str] = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]

# Application definition
INSTALLED_APPS = COMMON_INSTALLED_APPS + [
    'users.apps.UsersConfig',
]

MIDDLEWARE = COMMON_MIDDLEWARE

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_ROOT / 'users' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': COMMON_TEMPLATE_CONTEXT_PROCESSORS,
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_ROOT / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = COMMON_AUTH_PASSWORD_VALIDATORS


# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    PROJECT_ROOT / 'users' / 'static',
]
STATIC_ROOT = PROJECT_ROOT / 'staticfiles'


# Custom user model
AUTH_USER_MODEL = 'users.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend',
]

# JWT settings (backward compatibility)
JWT_SECRET = os.getenv('JWT_SECRET', 'change-me-in-production')
JWT_ALGORITHM = os.getenv('JWT_ALGORITHM', 'HS256')
JWT_EXP_DELTA_SECONDS = int(os.getenv('JWT_EXP_DELTA_SECONDS', str(14 * 24 * 3600)))

# django-ninja-jwt settings
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=JWT_EXP_DELTA_SECONDS),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': JWT_ALGORITHM,
    'SIGNING_KEY': JWT_SECRET,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'sub',
    'USER_AUTHENTICATION_RULE': 'ninja_jwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('users.tokens.CustomAccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# Jazzmin configuration
JAZZMIN_SETTINGS = {
    **COMMON_JAZZMIN_SETTINGS,
    'site_title': 'User Admin',
    'site_header': 'User Administration',
    'site_brand': 'User',
    'welcome_sign': 'User Admin',
    'copyright': 'User Project',
    'search_model': ['users.User', 'users.Service', 'users.Role', 'users.Permission'],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'users.Permission': 'fas fa-key',
        'users.Role': 'fas fa-user-tag',
        'users.Service': 'fas fa-cubes',
        'users.User': 'fas fa-user-circle',
    },
}
