# Generated by Django 6.0 on 2025-12-23 05:02

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'last_login',
                    models.DateTimeField(blank=True, null=True, verbose_name='last login'),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={'unique': 'A user with that username already exists.'},
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(blank=True, max_length=150, verbose_name='first name'),
                ),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=150, verbose_name='last name'),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='date joined'
                    ),
                ),
                ('name', models.CharField(help_text='User full name', max_length=255)),
                (
                    'email',
                    models.EmailField(help_text='User email address', max_length=254, unique=True),
                ),
                (
                    'email_confirmed',
                    models.BooleanField(default=False, help_text='Whether email is confirmed'),
                ),
                (
                    'email_confirmed_at',
                    models.DateTimeField(
                        blank=True, help_text='When email was confirmed', null=True
                    ),
                ),
                (
                    'credits',
                    models.PositiveBigIntegerField(default=0, help_text='Current credits balance.'),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'amount',
                    models.IntegerField(help_text='Credits added (positive) or spent (negative).'),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('purchase', 'Purchase'),
                            ('spend', 'Spend'),
                            ('adjustment', 'Adjustment'),
                            ('refund', 'Refund'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Human-readable notes describing why this transaction happened.',
                        max_length=255,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['user', '-created_at'], name='qr_code_cre_user_id_3577de_idx'
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'name',
                    models.CharField(
                        default='Untitled QR Code', help_text='Name of the QR code', max_length=255
                    ),
                ),
                (
                    'qr_type',
                    models.CharField(
                        choices=[('url', 'URL'), ('text', 'Text')],
                        help_text='Type of QR code content',
                        max_length=10,
                    ),
                ),
                (
                    'content',
                    models.TextField(help_text='The actual content encoded in the QR code'),
                ),
                (
                    'original_url',
                    models.URLField(
                        blank=True,
                        help_text='Original URL if content is a shortened URL',
                        max_length=2000,
                        null=True,
                    ),
                ),
                (
                    'use_url_shortening',
                    models.BooleanField(default=False, help_text='Whether to use URL shortening'),
                ),
                (
                    'short_code',
                    models.CharField(
                        blank=True,
                        help_text='Short code for URL shortening',
                        max_length=16,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'qr_format',
                    models.CharField(
                        choices=[('png', 'PNG'), ('svg', 'SVG'), ('pdf', 'PDF')],
                        default='png',
                        max_length=10,
                    ),
                ),
                (
                    'size',
                    models.IntegerField(default=10, help_text='Scale factor for QR code size'),
                ),
                (
                    'error_correction',
                    models.CharField(
                        choices=[
                            ('L', 'Low (~7%)'),
                            ('M', 'Medium (~15%)'),
                            ('Q', 'Quartile (~25%)'),
                            ('H', 'High (~30%)'),
                        ],
                        default='M',
                        max_length=1,
                    ),
                ),
                ('border', models.IntegerField(default=4, help_text='Border size (quiet zone)')),
                (
                    'background_color',
                    models.CharField(
                        default='white',
                        help_text='Background color (hex, name, or "transparent")',
                        max_length=20,
                    ),
                ),
                (
                    'foreground_color',
                    models.CharField(
                        default='black', help_text='Foreground (data) color', max_length=20
                    ),
                ),
                (
                    'image_file',
                    models.CharField(help_text='Path to generated image file', max_length=255),
                ),
                (
                    'scan_count',
                    models.IntegerField(default=0, help_text='Number of times QR code was scanned'),
                ),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                (
                    'deleted_at',
                    models.DateTimeField(
                        blank=True, help_text='Timestamp when QR code was soft-deleted', null=True
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='qrcodes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['short_code'], name='qr_code_qrc_short_c_2d88a2_idx'),
                    models.Index(
                        fields=['created_by', '-created_at'], name='qr_code_qrc_created_c7ecb5_idx'
                    ),
                    models.Index(fields=['deleted_at'], name='qr_code_qrc_deleted_109f43_idx'),
                ],
            },
        ),
    ]
