# Generated by Django 6.1.1 on 2026-09-27 23:08

import apps.file_transfer.models.transfer
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransferSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('logged_in_max_file_size_bytes', models.PositiveBigIntegerField(default=5368709120, verbose_name='Max file size (bytes)')),
                ('logged_in_max_files', models.PositiveIntegerField(default=100)),
                ('logged_in_max_total_size_bytes', models.PositiveBigIntegerField(default=21474836480, verbose_name='Max total size (bytes)')),
                ('logged_in_max_recipients', models.PositiveIntegerField(default=20)),
                ('anonymous_enabled', models.BooleanField(default=False)),
                ('anonymous_max_file_size_bytes', models.PositiveBigIntegerField(default=2147483648)),
                ('anonymous_max_files', models.PositiveIntegerField(default=20)),
                ('anonymous_max_total_size_bytes', models.PositiveBigIntegerField(default=5368709120)),
                ('anonymous_max_recipients', models.PositiveIntegerField(default=10)),
                ('anonymous_max_transfers_per_ip_per_day', models.PositiveIntegerField(default=5)),
                ('anonymous_max_bytes_per_ip_per_day', models.PositiveBigIntegerField(default=5368709120)),
                ('anonymous_allowed_expiry_days', models.CharField(default='1,5,15,30', help_text='Comma-separated allowed expiry values (in days) offered to anonymous senders.', max_length=64)),
                ('price_per_gb_per_day', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), help_text='Credits charged per GB stored per day, for logged-in senders.', max_digits=10)),
                ('suspension_grace_days', models.PositiveIntegerField(default=7, help_text='Days a suspended (out-of-credits) transfer is kept before its files are deleted, if not topped up.')),
            ],
            options={
                'verbose_name': 'File transfer settings',
                'verbose_name_plural': 'File transfer settings',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(blank=True, default='', help_text='Set for anonymous senders.', max_length=254)),
                ('slug', models.CharField(default=apps.file_transfer.models.transfer.generate_slug, editable=False, max_length=32, unique=True)),
                ('manage_token', models.CharField(blank=True, default=apps.file_transfer.models.transfer.generate_manage_token, editable=False, max_length=64)),
                ('message', models.TextField(blank=True, default='', max_length=2000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_confirmation', 'Pending confirmation'), ('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='draft', max_length=24)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('notify_on_download', models.BooleanField(default=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_billed_at', models.DateTimeField(blank=True, null=True)),
                ('accrued', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Fractional credits owed but not yet spent (billing.spend_credits only takes whole credits); see apps.file_transfer.services.metering.', max_digits=14)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('billed_days', models.PositiveIntegerField(default=0, help_text='Number of days metered so far, for the credit ledger description (e.g. "Transfer \\"report.pdf\\", day 3").')),
                ('credits_charged', models.PositiveIntegerField(default=0, help_text='Running total of whole credits spent for this transfer so far (dashboard display; billing.CreditTransaction has no FK back here -- billing may not import file_transfer -- so this is the only place that total lives).')),
                ('expiry_notified_at', models.DateTimeField(blank=True, help_text='When the "expires tomorrow" email was sent.', null=True)),
                ('zip_status', models.CharField(choices=[('none', 'Not requested'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=16)),
                ('zip_key', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null for an anonymous transfer (phase 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 checksum from S3, base64.', max_length=128)),
                ('upload_id', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='file_transfer.transfer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='file_transfer.transfer')),
                ('file', models.ForeignKey(blank=True, help_text='Null means the zip (phase 2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to='file_transfer.transferfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='file_transfer.transfer')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['slug'], name='file_transf_slug_4c0ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['owner', 'status'], name='file_transf_owner_i_90f5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'expires_at'], name='file_transf_status_9ec502_idx'),
        ),
        migrations.AddIndex(
            model_name='transferfile',
            index=models.Index(fields=['transfer'], name='file_transf_transfe_cfb48a_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadevent',
            index=models.Index(fields=['transfer', '-created_at'], name='file_transf_transfe_61b314_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrecipient',
            constraint=models.UniqueConstraint(fields=('transfer', 'email'), name='unique_transfer_recipient'),
        ),
    ]
