# Generated by Django 6.1.1 on 2026-09-28 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='anon_cookie_id',
            field=models.CharField(blank=True, default='', help_text='Opaque id from the signed anonymous-sender cookie, used alongside sender_ip for the per-day caps (spec section 13).', max_length=64),
        ),
        migrations.AddField(
            model_name='transfer',
            name='email_verification_id',
            field=models.UUIDField(blank=True, help_text="The apps.core EmailVerification row backing this transfer's pending anonymous-sender confirmation.", null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP that created the transfer (anonymous only).', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text="The Django session key that created this draft, so only that browser session may upload to or finalize it before it's confirmed. See apps.file_transfer.services.anonymous.", max_length=40),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_ip', 'created_at'], name='file_transf_sender__e972f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['anon_cookie_id', 'created_at'], name='file_transf_anon_co_4fe8bb_idx'),
        ),
    ]
