# Generated by Django 6.1.1 on 2026-09-28 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='anon_cookie_id',
            field=models.CharField(blank=True, default='', help_text='Opaque id from the signed anonymous-sender cookie, used alongside sender_ip for the per-day caps (spec section 13).', max_length=64),
        ),
        migrations.AddField(
            model_name='transfer',
            name='email_verification_id',
            field=models.UUIDField(blank=True, help_text="The apps.core EmailVerification row backing this transfer's pending anonymous-sender confirmation.", null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP that created the transfer (anonymous only).', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='draft_token_hash',
            field=models.CharField(blank=True, default='', help_text="HMAC-SHA256 digest of a random per-draft token kept in the session that created this draft, so only that browser session may upload to or finalize it before it's confirmed. Deliberately not the session's own key (which django.contrib.auth.login() rotates, and which would otherwise leak a real, authenticated session key into this read-only admin list) -- see apps.file_transfer.services.anon_session.", max_length=64),
        ),
        migrations.AddField(
            model_name='transfer',
            name='zip_build_started_at',
            field=models.DateTimeField(blank=True, help_text="When the current (or most recent) zip build claimed `zip_status=BUILDING`. Lets a build that never finished (a worker restart mid-build) be re-claimed once it is older than `services.zip`'s lease, instead of leaving the download page polling `BUILDING` forever.", null=True),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['sender_ip', 'created_at'], name='file_transf_sender__e972f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['anon_cookie_id', 'created_at'], name='file_transf_anon_co_4fe8bb_idx'),
        ),
    ]
