# Generated by Django 6.1.1 on 2026-09-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0002_transfer_anon_cookie_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='client_last_modified',
            field=models.BigIntegerField(blank=True, help_text="The browser File object's `lastModified` (ms since epoch) at the time this file was added, if the client supplied one. Used together with name and size to match a file the sender re-selects after a page reload back to this row, so its upload can resume instead of restarting (spec: resumable uploads) -- see apps.file_transfer.services.uploads.", null=True),
        ),
    ]
