# Generated by Django 6.1.1 on 2026-09-28 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_transfer', '0003_transferfile_client_last_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfersettings',
            name='auto_hold_report_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Put a transfer on hold (see Transfer.held_for_review_at) once it has this many pending abuse reports from distinct IPs. 0 (the default) turns this off -- every transfer still needs an admin to look at its reports either way.'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='held_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='takedown_reason',
            field=models.TextField(blank=True, default='', help_text="Staff-authored reason. Always shown on the sender's dashboard, and included in the takedown email if the sender is notified -- never the identity of whoever reported it. For anything that should stay internal, use the staff-only note field instead."),
        ),
        migrations.AddField(
            model_name='transfer',
            name='takedown_internal_note',
            field=models.TextField(blank=True, default='', help_text='Staff-only note about this takedown -- never shown to the sender, on the dashboard or in any email.'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='takedown_notify',
            field=models.BooleanField(default=False, help_text="Whether staff chose to email the sender when this transfer was taken down. Recorded on the transfer (rather than only passed to `services.takedown.take_down_transfer`'s own `notify` argument) so `jobs.expire_transfers`'s deferred-deletion sweep -- which finishes the S3 delete, and only then fires the notification, for any transfer whose deletion was deferred -- honours the choice staff actually made for a takedown, rather than defaulting to every other ended transfer's always-notify behaviour."),
        ),
        migrations.AddField(
            model_name='transfer',
            name='taken_down_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='taken_down_by',
            field=models.ForeignKey(blank=True, help_text='The staff user who took this transfer down, via apps.file_transfer.admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_confirmation', 'Pending confirmation'), ('active', 'Active'), ('disabled', 'Disabled'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('deleted', 'Deleted'), ('taken_down', 'Taken down')], default='draft', max_length=24),
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'permissions': [('takedown_transfer', 'Can take down a transfer, release an abuse-review hold, or dismiss a report (issue #59)')]},
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('malware', 'Malware'), ('copyright', 'Copyright infringement'), ('illegal_content', 'Illegal content'), ('phishing_spam', 'Phishing or spam'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True, default='', max_length=2000)),
                ('reporter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The staff user who dismissed this report or took its transfer down.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='file_transfer.transfer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transfer', 'status'], name='file_transf_transfe_309e87_idx'), models.Index(fields=['status', 'created_at'], name='file_transf_status_196d14_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedSender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('ip', 'IP / CIDR')], max_length=8)),
                ('value', models.CharField(help_text='An exact email or "*@domain" wildcard (kind=Email; matches only that exact domain, not its subdomains -- \'*@example.com\' does not match \'someone@mail.example.com\'), or an IP address or CIDR range (kind=IP/CIDR).', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Blank means this block never expires.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'value'], name='file_transf_kind_79c8e8_idx')],
            },
        ),
    ]
