# Generated by Django 6.0 on 2025-12-29 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'amount',
                    models.IntegerField(help_text='Credits added (positive) or spent (negative).'),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('purchase', 'Purchase'),
                            ('spend', 'Spend'),
                            ('adjustment', 'Adjustment'),
                            ('refund', 'Refund'),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Human-readable notes describing why this transaction happened.',
                        max_length=255,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credit_transactions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['user', '-created_at'], name='users_credi_user_id_1e22dd_idx'
                    )
                ],
            },
        ),
    ]
