# Generated by Django 6.0 on 2025-12-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_credits_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Whether email is confirmed'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When email was confirmed', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0, help_text='Current credits balance.'),
        ),
    ]
