# Generated by Django 6.0.4 on 2026-09-26 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.PositiveBigIntegerField(default=0, help_text='Current balance.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Credits added (positive) or spent (negative).')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('spend', 'Spend'), ('adjustment', 'Adjustment'), ('refund', 'Refund')], max_length=32)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable notes describing why this transaction happened.', max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='Label of the app that caused this change (e.g. `qr_code`); blank for admin.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_cre_user_id_b1ca8c_idx')],
            },
        ),
    ]
