from .pages import (
    account_created_page,
    account_page,
    confirm_email_page,
    credits_history_page,
    dashboard,
    email_confirmation_success,
    forgot_password_page,
    home_page,
    login_page,
    logout_page,
    qrcode_duplicate,
    qrcode_editor,
    register_page,
    reset_password_page,
)

__all__ = [
    'account_created_page',
    'account_page',
    'credits_history_page',
    'confirm_email_page',
    'dashboard',
    'email_confirmation_success',
    'forgot_password_page',
    'home_page',
    'login_page',
    'logout_page',
    'qrcode_editor',
    'qrcode_duplicate',
    'register_page',
    'reset_password_page',
]
