# Generated by Django 6.1.1 on 2026-09-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('interval_seconds', models.PositiveIntegerField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('run_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scheduled job',
                'verbose_name_plural': 'Scheduled jobs',
                'ordering': ['name'],
            },
        ),
    ]
