# Generated by Django 6.1.1 on 2026-09-28 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('email_verification_code_length', models.PositiveSmallIntegerField(default=6, help_text='Number of digits in a generated email verification code.', verbose_name='Verification code length')),
                ('email_verification_validity_minutes', models.PositiveIntegerField(default=30, help_text='How long an email verification code/link stays valid after it is sent.', verbose_name='Verification validity (minutes)')),
                ('email_verification_max_attempts', models.PositiveSmallIntegerField(default=5, help_text='Wrong codes allowed before a verification is burned and a resend is required.', verbose_name='Verification max attempts')),
                ('email_verification_resend_cooldown_seconds', models.PositiveIntegerField(default=60, help_text='Minimum time between two verification sends for the same email+purpose.', verbose_name='Verification resend cooldown (seconds)')),
            ],
            options={
                'verbose_name': 'Core settings',
                'verbose_name_plural': 'Core settings',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(max_length=100)),
                ('code_hash', models.CharField(max_length=64)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='Set when a newer verification for the same email+purpose supersedes this one.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email verification',
                'verbose_name_plural': 'Email verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='core_emailv_email_9b33a4_idx')],
            },
        ),
    ]
