# Generated by Django 6.1.1 on 2026-09-28 04:33
# Issue #53 code review: replaces this PR's original `0003_ratelimit_cache_table.py` (a
# `createcachetable` `RunPython` migration for a `DatabaseCache`-backed `'ratelimit'` cache alias)
# with a normal model table -- rewritten in place rather than added as a follow-up migration since
# this PR was still unmerged. See `apps.core.models.RateLimitCounter` and
# `apps.core.ratelimit.limiter` for why: `DatabaseCache.incr` isn't atomic and doesn't preserve a
# key's TTL past the cache's default timeout, and its `MAX_ENTRIES` culling could evict other
# rules' still-live counters under ordinary traffic.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coresettings_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Rate limit counter',
                'verbose_name_plural': 'Rate limit counters',
            },
        ),
    ]
