"""
Django settings for qr_code service.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: PROJECT_ROOT / 'subdir'.
# PROJECT_ROOT, aka BASE_DIR.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Add parent directory to path for common imports
sys.path.insert(0, str(PROJECT_ROOT.parent))

# Load environment variables from the selected `.env.<ENVIRONMENT>` file.
# This must happen before reading any `os.getenv(...)` values.
try:
    # Test runs and static analysis may have multiple env files in the repo; default to dev.
    if 'pytest' in sys.modules or 'mypy' in sys.modules:
        os.environ.setdefault('ENVIRONMENT', 'dev')

    from common.environment import select_env

    _selection = select_env(PROJECT_ROOT)
    if _selection.errors:
        raise RuntimeError('\n'.join(_selection.errors))
    if _selection.environment:
        os.environ.setdefault('ENVIRONMENT', _selection.environment)
        load_dotenv(dotenv_path=_selection.env_path)
    else:
        raise RuntimeError('Environment not set.')
except Exception:
    # Fail fast if env selection is broken; otherwise we'd silently read wrong defaults.
    raise

# Import common settings
from common.settings.base import (  # noqa: E402, F401
    COMMON_INSTALLED_APPS,
    COMMON_JAZZMIN_SETTINGS,
    COMMON_TEMPLATE_CONTEXT_PROCESSORS,
    DEFAULT_AUTO_FIELD,
    LANGUAGE_CODE,
    TIME_ZONE,
    USE_I18N,
    USE_TZ,
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-8eho-(3@jki^spuj0q%+k!m9a@%d82mqy+fxe65w)6jr_e=ld2'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ['true', '1']

ALLOWED_HOSTS: list[str] = [
    h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]


# Application definition
INSTALLED_APPS = COMMON_INSTALLED_APPS + [
    'ninja_extra',
    'ninja_jwt',
    'qr_code',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_ROOT / 'qr_code' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': COMMON_TEMPLATE_CONTEXT_PROCESSORS,
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_ROOT / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# Override common validators with custom min_length of 6 for qr_code service
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    PROJECT_ROOT / 'qr_code' / 'static',
    PROJECT_ROOT.parent / 'common' / 'static',
]
STATIC_ROOT = PROJECT_ROOT / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = PROJECT_ROOT / 'media'


# Custom user model
AUTH_USER_MODEL = 'qr_code.User'

# Login URL for @login_required decorator
LOGIN_URL = '/login/'

# QR Code settings
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8010')
QR_CODE_REDIRECT_PATH = '/go/'

# Password reset settings
PASSWORD_RESET_TOKEN_TTL_HOURS = int(os.getenv('PASSWORD_RESET_TOKEN_TTL_HOURS', '4'))

# Email confirmation settings
EMAIL_CONFIRMATION_TOKEN_TTL_HOURS = int(os.getenv('EMAIL_CONFIRMATION_TOKEN_TTL_HOURS', '48'))

# Django Ninja JWT Settings
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'ninja_jwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('ninja_jwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Email settings
# Comma-separated list of email backends to use. Example: "console" or "ses,console".
EMAIL_BACKENDS = os.getenv('EMAIL_BACKENDS', '')

# Tests should not require external configuration.
if not EMAIL_BACKENDS:
    import sys

    if 'pytest' in sys.modules:
        EMAIL_BACKENDS = 'console'

AWS_SES_SENDER = os.getenv('AWS_SES_SENDER', 'no-reply@example.com')

# Jazzmin configuration
JAZZMIN_SETTINGS = {
    **COMMON_JAZZMIN_SETTINGS,
    'site_title': 'QR Code Admin',
    'site_header': 'QR Code Administration',
    'site_brand': 'QR Code',
    'welcome_sign': 'QR Code Admin',
    'copyright': 'QR Code Project',
    'search_model': ['qr_code.User', 'qr_code.QRCode'],
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'qr_code.QRCode': 'fas fa-qrcode',
        'qr_code.User': 'fas fa-user-circle',
    },
    'custom_links': {
        'qr_code': [
            {
                'name': 'Admin Tools',
                'url': '/admin/tools/',
                'permissions': ['auth.add_user'],
                'icon': 'fas fa-tools',
            }
        ],
    },
}
